name: test node dependancies workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install dependancies
        working-directory: node-module
        run: npm i
      - name: run test
        working-directory: node-module
        run: npm run test
